### PR TITLE
Added SQL file for weight

### PR DESCRIPTION
**Pull request by NotPixel**
- Added SQL file for people with weight version
- Changed some of the README.MD, up to you if you'd like to use it

### CODE REVIEW

**Comment by yagizher** [comment]
Good. But useless till someone changes item checks, and removals in server.

**Comment by NotPixel** [comment]
What do you mean by that?
All that really does is allow you to add it to any items table so long as the default values are set for to the reset of your columns.

**Comment by utkuali** [comment]
What'up with that README.md changes?

**Comment by yagizher** [comment]
Utku, grammar hatalarını veya fazla kelimeleri eksiltmiş yanlış anlaşılmaması veya kafa karıştırmaması için.

**Pull request closed without merging**
